export const SONG_PATH = 'http://localhost:3000/song';
export const UPLOAD_END_POINT = 'http://localhost:8888/api/v1/upload';
export const APPLICATION_SHOW_SETTINGS = 'APPLICATION_SHOW_SETTINGS';
export const APPLICATION_SHOW_COLOR_PICKER = 'APPLICATION_SHOW_COLOR_PICKER';
export const APPLICATION_SET_TOOLBAR_COLOR = 'APPLICATION_SET_TOOLBAR_COLOR';
export const APPLICATION_SET_PLAYER_COLOR = 'APPLICATION_SET_PLAYER_COLOR';

export const AUTH0_CLIENT_ID = 'JWnTdqYQsz1COi783JXsqba0p0AGNL0Q';
export const AUTH0_DOMAIN = 'quanzhi.auth0.com';
