export const SONG_PATH = 'http://localhost:3000/song/';
export const APPLICATION_SHOW_SETTINGS = 'APPLICATION_SHOW_SETTINGS';
export const APPLICATION_SHOW_COLOR_PICKER = 'APPLICATION_SHOW_COLOR_PICKER';
export const APPLICATION_SET_TOOLBAR_COLOR = 'APPLICATION_SET_TOOLBAR_COLOR';
export const APPLICATION_SET_PLAYER_COLOR = 'APPLICATION_SET_PLAYER_COLOR';
