export const SONG_CHANGE_PLAYING = 'SONG_CHANGE_PLAYING';
export const SONG_PLAYER_STATUS = 'SONG_PLAYER_STATUS';
export const SONG_CHANGE_PLAY_MODE = 'SONG_CHANGE_PLAY_MODE';
export const SONG_PLAYLIST_CHANGE = 'SONG_PLAYLIST_CHANGE';