export const SONG_CHANGE_PLAYING = 'SONG_CHANGE_PLAYING';
export const SONG_PLAYER_STATUS = 'SONG_PLAYER_STATUS';
export const SONG_CHANGE_PLAY_MODE = 'SONG_CHANGE_PLAY_MODE';
export const SONG_PLAYLIST_CHANGE = 'SONG_PLAYLIST_CHANGE';

export const SONG_PLAY_MODE_LOOP = 'SONG_PLAY_MODE_LOOP';
export const SONG_PLAY_MODE_REPEAT = 'SONG_PLAY_MODE_REPEAT';
export const SONG_PLAY_MODE_SHUFFLE = 'SONG_PLAY_MODE_SHUFFLE';