export const FILE_UPLOADING = 'FILE_UPLOADING';
export const FILE_SET_FILES = 'FILE_SET_FILES';
export const FILE_SET_COVERS = 'FILE_SET_COVERS';
export const FILE_ADD_COVER = 'FILE_ADD_COVER';
export const FILE_ADD_MUSIC_INFO = 'FILE_ADD_MUSIC_INFO';